<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>NoThanksKeepIt</AssemblyName>

		<UniqueId>ceddieeee.NoThanksKeepIt</UniqueId>
		<Name>No Thanks, Keep It</Name>
		<Authors>ceddieeee</Authors>
		<Description>NPCs return hated and disliked gifts back to your inventory.</Description>
		<Version>1.0.0</Version>
		<MinimumApiVersion>auto</MinimumApiVersion>
		<MinimumGameVersion_Behavior>SetFull</MinimumGameVersion_Behavior>
		<UpdateKeys>Nexus:45862</UpdateKeys>
	</PropertyGroup>

	<PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<EnableHarmony>true</EnableHarmony>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Leclair.Stardew.ModManifestBuilder" Version="2.4.1" />
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.4.0" />
    <PackageReference Include="Pathoschild.Stardew.ModTranslationClassBuilder" Version="2.2.1" />
  </ItemGroup>

</Project>
